[package]
authors = ["Thomas Bahn <thomas@thomas-bahn.net>"]
description = "A SCRAM provider library."
keywords = ["scram", "authentication"]
license = "MIT"
name = "scram"
repository = "https://github.com/tomprogrammer/scram"
documentation = "https://tomprogrammer.github.io/scram/scram/index.html"
readme = "README.md"
version = "0.1.0"

[dependencies]
data-encoding = "1.1.2"
rand = "0.3.14"
ring = "0.5"
